"use client";

import { useEffect, useState } from "react";
import { Navbar } from "@/components/layout/Navbar";
import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { Badge } from "@/components/ui/Badge";
import { ArrowUpRight, Truck, Package, Activity, Ban, Loader2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useSession } from "@/lib/sessionContext";

export default function AdminDashboardPage() {
  const { user, token, loading: sessionLoading } = useSession();
  const [shipments, setShipments] = useState<any[]>([]);
  const [users, setUsers] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState(false);
  
  // Driver Form
  // const [showDriverForm, setShowDriverForm] = useState(false);
  // const [driverData, setDriverData] = useState({
  //   name: '', email: '', phone: '', address: '', vehicleType: '', 
  //   licenseNumber: '', nin: '', guarantor_name: '', guarantor_phone: '', 
  //   guarantor_address: '', guarantor_nin: ''
  // });

  const router = useRouter();

  const fetchData = async () => {
    if (!token) return;
    try {
      const [shipRes, userRes] = await Promise.all([
        fetch("https://transly-wr1m.onrender.com/admin/shipments", { headers: { Authorization: `Bearer ${token}` }, credentials: "include" }),
        fetch("https://transly-wr1m.onrender.com/admin/users", { headers: { Authorization: `Bearer ${token}` }, credentials: "include" })
      ]);
      const shipData = await shipRes.json();
      const userData = await userRes.json();
      if (shipData.success) setShipments(shipData.shipments);
      if (userData.success) setUsers(userData.users);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!sessionLoading) {
        if (!user || user.role !== 'admin') {
            router.push("/dashboard");
            return;
        }
        fetchData();
    }
  }, [sessionLoading, user, router]);

  const drivers = users.filter(u => u.role === "driver");

  const assignDriver = async (shipmentId: number, driverId: string) => {
    if(!driverId) return;
    setActionLoading(true);
    try {
      await fetch("https://transly-wr1m.onrender.com/admin/assign-driver", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        credentials: "include",
        body: JSON.stringify({ shipmentId, driverId })
      });
      fetchData();
    } catch(err) {
      console.error(err);
    } finally {
      setActionLoading(false);
    }
  };

  const toggleSuspend = async (userId: string) => {
    setActionLoading(true);
    try {
      await fetch(`https://transly-wr1m.onrender.com/admin/users/${userId}/suspend`, {
        method: "PUT",
        headers: { Authorization: `Bearer ${token}` },
        credentials: "include"
      });
      fetchData();
    } catch(err) {
      console.error(err);
    } finally {
      setActionLoading(false);
    }
  }

  // const handleDriverRegister = async (e: React.FormEvent) => {
  //   e.preventDefault();
  //   try {
  //     const res = await fetch("https://transly-wr1m.onrender.com/admin/driver", {
  //       method: "POST",
  //       headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
  //       body: JSON.stringify(driverData)
  //     });
  //     if(res.ok) {
  //       setShowDriverForm(false);
  //       fetchData();
  //       alert('Driver created successfully with autogenerated password');
  //     } else {
  //       const error = await res.json();
  //       alert(error.error || "Failed to create driver");
  //     }
  //   } catch(err) { alert(err) }
  // }

  if (loading) return (
    <div className="min-h-[400px] flex flex-col items-center justify-center p-10 bg-white/50 rounded-3xl border border-dashed border-slate-200 m-8">
        <Loader2 className="h-12 w-12 animate-spin text-orange-600 mb-4" />
        <p className="text-slate-500 font-bold tracking-tight">Initializing platform overview...</p>
    </div>
  );

  return (
    <div className="min-h-screen bg-slate-50 pb-12">
      {/* <Navbar /> */}
      <div className="container mx-auto max-w-7xl">
        <div className="mb-8 flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Super Admin Overview</h1>
            <p className="text-sm text-slate-500 mt-1">Monitor shipments, override requests, and manage workforce.</p>
          </div>
          {/* <Button onClick={() => setShowDriverForm(!showDriverForm)} className="shadow-md py-5 bg-orange-600 hover:bg-orange-700">
             {showDriverForm ? 'Close Registration' : 'Register New Driver'}
          </Button> */}
        </div>

        {/* {showDriverForm && (
          <Card className="mb-8 border-orange-500 ring-1 ring-orange-500 shadow-xl glass">
            <CardHeader className="bg-orange-50/50 border-b border-orange-100 rounded-t-xl pb-4 mb-4">
              <CardTitle className="text-orange-900">Manual Driver Registration</CardTitle>
              <CardDescription>Onboard a driver into the system bypassing public auth routing.</CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleDriverRegister} className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input placeholder="Full Name" required onChange={e => setDriverData({...driverData, name: e.target.value})} />
                <Input placeholder="Email Address" type="email" required onChange={e => setDriverData({...driverData, email: e.target.value})} />
                <Input placeholder="Phone Number" required onChange={e => setDriverData({...driverData, phone: e.target.value})} />
                <Input placeholder="Home Address" required onChange={e => setDriverData({...driverData, address: e.target.value})} />
                <Input placeholder="National ID (NIN) Number" required onChange={e => setDriverData({...driverData, nin: e.target.value})} />
                <div className="grid grid-cols-2 gap-2">
                  <Input placeholder="Vehicle Type (e.g. Van, Truck)" required onChange={e => setDriverData({...driverData, vehicleType: e.target.value})} />
                  <Input placeholder="License Plate Number" required onChange={e => setDriverData({...driverData, licenseNumber: e.target.value})} />
                </div>
                
                <h3 className="md:col-span-2 font-bold text-slate-700 mt-4 pt-4 border-t">Guarantor Information</h3>
                <Input placeholder="Guarantor Name" required onChange={e => setDriverData({...driverData, guarantor_name: e.target.value})} />
                <Input placeholder="Guarantor Phone" required onChange={e => setDriverData({...driverData, guarantor_phone: e.target.value})} />
                <Input placeholder="Guarantor Address" required onChange={e => setDriverData({...driverData, guarantor_address: e.target.value})} />
                <Input placeholder="Guarantor NIN" required onChange={e => setDriverData({...driverData, guarantor_nin: e.target.value})} />

                <div className="md:col-span-2 mt-4 flex justify-end">
                  <Button type="submit" className="bg-slate-900 w-full md:w-auto text-lg px-10">Submit Identity Profiles</Button>
                </div>
              </form>
            </CardContent>
          </Card>
        )} */}

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
           <Card className="border-0 shadow-sm rounded-2xl glass overflow-hidden">
             <CardHeader className="bg-slate-100/50">
               <CardTitle>System Accounts</CardTitle>
             </CardHeader>
             <CardContent className="p-0">
               <div className="max-h-96 overflow-y-auto">
                 <table className="w-full text-sm text-left">
                   <thead className="bg-slate-50 border-b sticky top-0">
                     <tr>
                       <th className="px-4 py-3 font-semibold text-slate-500">Name / Role</th>
                       <th className="px-4 py-3 font-semibold text-slate-500">Contact</th>
                       <th className="px-4 py-3 font-semibold text-slate-500 text-right">Settings</th>
                     </tr>
                   </thead>
                   <tbody>
                     {users.map(u => (
                       <tr key={u.id} className={`border-b ${u.is_suspended ? 'bg-red-50/50 opacity-80' : ''}`}>
                         <td className="px-4 py-3">
                           <div className="font-bold">{u.name}</div>
                           <Badge variant={u.role === 'admin' ? 'default' : u.role === 'driver' ? 'warning' : 'outline'} className="text-[10px] uppercase">{u.role}</Badge>
                         </td>
                         <td className="px-4 py-3 text-slate-500">{u.email}<br/>{u.phone}</td>
                         <td className="px-4 py-3 text-right">
                           <Button size="sm" variant={u.is_suspended ? "default" : "destructive"} onClick={() => toggleSuspend(u.id)} className="px-3" disabled={u.role === 'admin'}>
                             {u.is_suspended ? 'Unsuspend' : 'Suspend'}
                           </Button>
                         </td>
                       </tr>
                     ))}
                   </tbody>
                 </table>
               </div>
             </CardContent>
           </Card>

           <Card className="border-0 shadow-sm rounded-2xl glass overflow-hidden">
            <CardHeader className="bg-slate-100/50">
              <CardTitle>Logistics Stream</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <div className="max-h-96 overflow-y-auto">
                <table className="w-full text-sm text-left">
                  <thead className="bg-slate-50 border-b sticky top-0">
                    <tr>
                      <th className="px-4 py-3 font-semibold text-slate-500">Tracking / Ref</th>
                      <th className="px-4 py-3 font-semibold text-slate-500">Driver Assignment</th>
                    </tr>
                  </thead>
                  <tbody>
                    {shipments.map((req: any) => (
                      <tr key={req.id} className="border-b">
                        <td className="px-4 py-3">
                          <div className="font-bold text-orange-600">{req.trackingNumber}</div>
                          <div className="text-xs text-slate-500">{req.origin} → {req.destination}</div>
                          <div className="flex gap-1 mt-1">
                             <Badge variant="outline" className="text-[10px]">{req.status.replace('_', ' ').toUpperCase()}</Badge>
                             <Badge variant={req.paymentStatus === 'paid' ? 'success' : 'error'} className="text-[10px]">
                               {(req.paymentStatus || 'unpaid').toUpperCase()}
                             </Badge>
                          </div>
                        </td>
                        <td className="px-4 py-3">
                          {req.status === 'pending' ? (
                            <select 
                              className="text-xs border rounded p-2 bg-slate-50 w-full disabled:opacity-50"
                              onChange={(e) => assignDriver(req.id, e.target.value)}
                              defaultValue=""
                              disabled={actionLoading}
                            >
                              <option value="" disabled>{actionLoading ? 'Allocating...' : 'Assign via Dispatch'}</option>
                              {drivers.map(d => <option key={d.id} value={d.id}>{d.name} ({d.email})</option>)}
                            </select>
                          ) : (
                            <div className="text-slate-800 font-medium">
                              Assigned Driver ID: <br/><span className="text-xs text-slate-500 truncate inline-block w-40">{req.driverId || 'N/A'}</span>
                            </div>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
