"use client";
import { Button } from "@/components/ui/Button";
import { Truck, Search, Mail, Phone, UserX, UserCheck, Eye, EyeOff, Loader2 } from "lucide-react";
import { useState, useEffect, useMemo } from "react";
import { Input } from "@/components/ui/Input";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";
import { useSession } from "@/lib/sessionContext";

export default function AdminDriversPage() {
    const { user, token, loading: sessionLoading } = useSession();
    // Driver Form
    const [showDriverForm, setShowDriverForm] = useState(false);
    const [showPassword, setShowPassword] = useState(false);
    const [driverData, setDriverData] = useState({
      name: '', email: '', phone: '', address: '', vehicleType: '', 
      licenseNumber: '', nin: '', guarantor_name: '', guarantor_phone: '', 
      guarantor_address: '', guarantor_nin: ''
    });

    const [drivers, setDrivers] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [actionLoading, setActionLoading] = useState(false);
    const [query, setQuery] = useState("");

    const fetchData = async () => {
    if (!token) return;
      try {
        const res = await fetch("https://transly-wr1m.onrender.com/admin/drivers", {
          headers: { Authorization: `Bearer ${token}` }
        });
        const data = await res.json();
        if (data.success) {
          setDrivers(data.drivers);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    useEffect(() => {
        if (!sessionLoading && token) {
            fetchData();
        }
    }, [sessionLoading, token]);

    const filteredDrivers = useMemo(() => {
      return drivers.filter((driver) => {
        const searchText = `${driver.id} ${driver.name} ${driver.email}`.toLowerCase();
        return query.trim() === "" || searchText.includes(query.toLowerCase());
      });
    }, [drivers, query]);

    const handleDriverRegister = async (e: React.FormEvent) => {
      e.preventDefault();
      setActionLoading(true);
      try {
        const res = await fetch("https://transly-wr1m.onrender.com/admin/driver", {
          method: "POST",
          headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
          body: JSON.stringify(driverData)
        });
        if(res.ok) {
          setShowDriverForm(false);
          fetchData();
          alert('Driver created successfully with autogenerated password');
        } else {
          const error = await res.json();
          alert(error.error || "Failed to create driver");
        }
      } catch(err) { 
        alert(err);
      } finally {
        setActionLoading(false);
      }
    }

    const toggleStatus = async (id: string) => {
      setActionLoading(true);
      try {
        const res = await fetch(`https://transly-wr1m.onrender.com/admin/users/${id}/suspend`, {
          method: "PUT",
          headers: { Authorization: `Bearer ${token}` }
        });
        const data = await res.json();
        if (data.success) {
          setDrivers(current => 
            current.map(d => d.id === id ? { ...d, is_suspended: data.is_suspended } : d)
          );
        }
      } catch (err) {
        console.error(err);
      } finally {
        setActionLoading(false);
      }
    };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Fleet & Drivers</h1>
          <p className="text-sm text-slate-500">Manage your active driver fleet.</p>
        </div>
         <Button onClick={() => setShowDriverForm(!showDriverForm)} className="shadow-md py-5 bg-orange-600 hover:bg-orange-700">
            <Truck className="h-4 w-4 mr-2" />  {showDriverForm ? 'Close Registration' : 'Register New Driver'}
         </Button>          
      </div>
      
      {showDriverForm && (
        <Card className="mb-8 border-orange-500 ring-1 ring-orange-500 shadow-xl glass">
          <CardHeader className="bg-orange-50/50 border-b border-orange-100 rounded-t-xl pb-4 mb-4">
            <CardTitle className="text-orange-900">Manual Driver Registration</CardTitle>
            <CardDescription>Onboard a driver into the system bypassing public auth routing.</CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleDriverRegister} className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Input placeholder="Full Name" required onChange={e => setDriverData({...driverData, name: e.target.value})} />
              <Input placeholder="Email Address" type="email" required onChange={e => setDriverData({...driverData, email: e.target.value})} />
              <Input placeholder="Phone Number" required onChange={e => setDriverData({...driverData, phone: e.target.value})} />
              <Input placeholder="Home Address" required onChange={e => setDriverData({...driverData, address: e.target.value})} />
              <Input placeholder="National ID (NIN) Number" required onChange={e => setDriverData({...driverData, nin: e.target.value})} />
              <div className="grid grid-cols-2 gap-2">
                <Input placeholder="Vehicle Type (e.g. Van, Truck)" required onChange={e => setDriverData({...driverData, vehicleType: e.target.value})} />
                <Input placeholder="License Plate Number" required onChange={e => setDriverData({...driverData, licenseNumber: e.target.value})} />
              </div>
              
              <h3 className="md:col-span-2 font-bold text-slate-700 mt-4 pt-4 border-t">Guarantor Information</h3>
              <Input placeholder="Guarantor Name" required onChange={e => setDriverData({...driverData, guarantor_name: e.target.value})} />
              <Input placeholder="Guarantor Phone" required onChange={e => setDriverData({...driverData, guarantor_phone: e.target.value})} />
              <Input placeholder="Guarantor Address" required onChange={e => setDriverData({...driverData, guarantor_address: e.target.value})} />
              <Input placeholder="Guarantor NIN" required onChange={e => setDriverData({...driverData, guarantor_nin: e.target.value})} />

              <div className="md:col-span-2 mt-4 flex justify-end">
                <Button disabled={actionLoading} type="submit" className="bg-slate-900 w-full md:w-auto text-lg px-10">
                    {actionLoading && <Loader2 className="h-4 w-4 animate-spin mr-2" />}
                    Submit Identity Profiles
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      )}

      <Card className="border-0 shadow-sm">
        <CardContent className="p-4 lg:p-6">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div className="relative w-full lg:max-w-xs">
              <Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" />
              <Input
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                placeholder="Search by driver ID, name, or email"
                className="pl-9"
              />
            </div>
          </div>
        </CardContent>
      </Card>

      <Card className="border-0 shadow-sm overflow-hidden">
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-sm text-left">
              <thead className="text-xs text-slate-500 bg-slate-50/80 uppercase border-b border-slate-100">
                <tr>
                  <th className="px-6 py-4 font-medium">Name</th>
                  <th className="px-6 py-4 font-medium">Contact</th>
                  <th className="px-6 py-4 font-medium">Vehicle Info</th>
                  <th className="px-6 py-4 font-medium">Status</th>
                  <th className="px-6 py-4 font-medium text-center">Actions</th>
                </tr>
              </thead>
              <tbody>
                {loading ? (
                  <tr>
                    <td colSpan={5} className="px-6 py-10 text-center">
                        <Loader2 className="h-8 w-8 animate-spin text-orange-600 mx-auto" />
                        <p className="text-sm text-slate-500 mt-2">Loading drivers list...</p>
                    </td>
                  </tr>
                ) : filteredDrivers.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="px-6 py-12 text-center">
                       <Truck className="h-12 w-12 text-slate-300 mx-auto mb-4" />
                       <h3 className="text-lg font-medium text-slate-900 mb-1">No drivers found</h3>
                       <p className="text-slate-500">Try adjusting your search query.</p>
                    </td>
                  </tr>
                ) : (
                  filteredDrivers.map((driver) => (
                    <tr key={driver.id} className="border-b border-slate-50 hover:bg-slate-50/50 transition-colors">
                      <td className="px-6 py-4 font-medium text-slate-900">{driver.name}</td>
                      <td className="px-6 py-4">
                        <div className="text-slate-500 flex items-center mb-1">
                          <Mail className="w-3 h-3 mr-2" /> {driver.email}
                        </div>
                        <div className="text-slate-500 flex items-center">
                          <Phone className="w-3 h-3 mr-2" /> {driver.phone || 'N/A'}
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <div className="font-medium text-slate-700">{driver.driverProfile?.vehicleType || 'N/A'}</div>
                        <div className="text-xs text-slate-500">{driver.driverProfile?.licenseNumber || 'N/A'}</div>
                      </td>
                      <td className={`px-6 py-4 font-medium ${!driver.is_suspended ? "text-emerald-600" : "text-slate-400"}`}>
                        {!driver.is_suspended ? "Active" : "Suspended"}
                      </td>
                      <td className="px-6 py-4 text-center">
                        <Button
                          variant="ghost"
                          size="icon"
                          disabled={actionLoading}
                          onClick={() => toggleStatus(driver.id)}
                          className={!driver.is_suspended ? "text-slate-400 hover:text-red-500" : "text-slate-400 hover:text-emerald-500"}
                        >
                          {actionLoading ? <Loader2 className="h-4 w-4 animate-spin text-orange-600" /> : (!driver.is_suspended ? <UserX className="h-4 w-4" /> : <UserCheck className="h-4 w-4" />)}
                        </Button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
