"use client";
import { Button } from "@/components/ui/Button";
import { Truck } from "lucide-react";
import { useState } from "react";
import { Input } from "@/components/ui/Input";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";



export default function AdminDriversPage() {

    // Driver Form
    const [showDriverForm, setShowDriverForm] = useState(false);
    const [driverData, setDriverData] = useState({
      name: '', email: '', phone: '', address: '', vehicleType: '', 
      licenseNumber: '', nin: '', guarantor_name: '', guarantor_phone: '', 
      guarantor_address: '', guarantor_nin: ''
    });
  

    const handleDriverRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    const token = localStorage.getItem("transly_token");
    try {
      const res = await fetch("http://localhost:9400/admin/driver", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify(driverData)
      });
      if(res.ok) {
        setShowDriverForm(false);
        fetchData();
        alert('Driver created successfully with autogenerated password');
      } else {
        const error = await res.json();
        alert(error.error || "Failed to create driver");
      }
    } catch(err) { alert(err) }
  }
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Fleet & Drivers</h1>
          <p className="text-sm text-slate-500">Manage your active driver fleet.</p>
        </div>
        {/* <Button>
          <Truck className="h-4 w-4 mr-2" /> Register Driver
        </Button> */}

         <Button onClick={() => setShowDriverForm(!showDriverForm)} className="shadow-md py-5 bg-orange-600 hover:bg-orange-700">
                   <Truck className="h-4 w-4 mr-2" />  {showDriverForm ? 'Close Registration' : 'Register New Driver'}
                  </Button>

                   
      </div>
      
      {showDriverForm && (
                            <Card className="mb-8 border-orange-500 ring-1 ring-orange-500 shadow-xl glass">
                              <CardHeader className="bg-orange-50/50 border-b border-orange-100 rounded-t-xl pb-4 mb-4">
                                <CardTitle className="text-orange-900">Manual Driver Registration</CardTitle>
                                <CardDescription>Onboard a driver into the system bypassing public auth routing.</CardDescription>
                              </CardHeader>
                              <CardContent>
                                <form onSubmit={handleDriverRegister} className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                  <Input placeholder="Full Name" required onChange={e => setDriverData({...driverData, name: e.target.value})} />
                                  <Input placeholder="Email Address" type="email" required onChange={e => setDriverData({...driverData, email: e.target.value})} />
                                  <Input placeholder="Phone Number" required onChange={e => setDriverData({...driverData, phone: e.target.value})} />
                                  <Input placeholder="Home Address" required onChange={e => setDriverData({...driverData, address: e.target.value})} />
                                  <Input placeholder="National ID (NIN) Number" required onChange={e => setDriverData({...driverData, nin: e.target.value})} />
                                  <div className="grid grid-cols-2 gap-2">
                                    <Input placeholder="Vehicle Type (e.g. Van, Truck)" required onChange={e => setDriverData({...driverData, vehicleType: e.target.value})} />
                                    <Input placeholder="License Plate Number" required onChange={e => setDriverData({...driverData, licenseNumber: e.target.value})} />
                                  </div>
                                  
                                  <h3 className="md:col-span-2 font-bold text-slate-700 mt-4 pt-4 border-t">Guarantor Information</h3>
                                  <Input placeholder="Guarantor Name" required onChange={e => setDriverData({...driverData, guarantor_name: e.target.value})} />
                                  <Input placeholder="Guarantor Phone" required onChange={e => setDriverData({...driverData, guarantor_phone: e.target.value})} />
                                  <Input placeholder="Guarantor Address" required onChange={e => setDriverData({...driverData, guarantor_address: e.target.value})} />
                                  <Input placeholder="Guarantor NIN" required onChange={e => setDriverData({...driverData, guarantor_nin: e.target.value})} />
                  
                                  <div className="md:col-span-2 mt-4 flex justify-end">
                                    <Button type="submit" className="bg-slate-900 w-full md:w-auto text-lg px-10">Submit Identity Profiles</Button>
                                  </div>
                                </form>
                              </CardContent>
                            </Card>
                          )}

      <Card className="border-0 shadow-sm">
        <CardContent className="p-12 text-center">
           <Truck className="h-12 w-12 text-slate-300 mx-auto mb-4" />
           <h3 className="text-lg font-medium text-slate-900 mb-1">No drivers available</h3>
           <p className="text-slate-500 max-w-sm mx-auto">Get started by onboarding your first fleet member.</p>
        </CardContent>
      </Card>
    </div>
  );
}
